(define (problem problem_2) (:domain imv)
(:objects 
  light1 heavy1 - ground_robot
  drone1 - drone

  alpha1 alpha2 alpha3 alpha4 alpha5 alpha6 alpha7 alpha8 alpha9 alpha10 - artifact_alpha
  beta1 beta2 beta3 beta4 beta5 beta6 beta7 beta8 beta9 beta10 - artifact_beta
)

(:init
  (connected entrance maintenance_tunnel)
  (connected maintenance_tunnel entrance)
  (connected hall_alpha maintenance_tunnel)
  (connected maintenance_tunnel hall_alpha)
  (connected hall_beta maintenance_tunnel)
  (connected maintenance_tunnel hall_beta)
  (connected stasis_lab maintenance_tunnel)
  (connected maintenance_tunnel stasis_lab)
  (connected pod_zone maintenance_tunnel)
  (connected maintenance_tunnel pod_zone)
  (connected cryo_chamber maintenance_tunnel)
  (connected maintenance_tunnel cryo_chamber)

  (stable entrance)
  (stable maintenance_tunnel)
  (stable hall_alpha)
  (stable stasis_lab)
  (stable pod_zone)
  (stable cryo_chamber)
  (unstable hall_beta)

  (normal_pressure entrance)
  (normal_pressure hall_alpha)
  (normal_pressure hall_beta)
  (normal_pressure stasis_lab)
  (normal_pressure cryo_chamber)
  (low_pressure maintenance_tunnel)
  (normal_pressure pod_zone)

  (pod_at pod1 pod_zone)
  (pod_at pod2 pod_zone)
  (pod_empty pod1)
  (pod_empty pod2)

  (artifact_at alpha1 hall_alpha)
  (artifact_at alpha2 hall_alpha)
  (artifact_at alpha3 hall_alpha)
  (artifact_at alpha4 hall_alpha)
  (artifact_at alpha5 hall_alpha)
  (artifact_at alpha6 hall_alpha)
  (artifact_at alpha7 hall_alpha)
  (artifact_at alpha8 hall_alpha)
  (artifact_at alpha9 hall_alpha)
  (artifact_at alpha10 hall_alpha)

  (is_not_cool alpha1)
  (is_not_cool alpha2)
  (is_not_cool alpha3)
  (is_not_cool alpha4)
  (is_not_cool alpha5)
  (is_not_cool alpha6)
  (is_not_cool alpha7)
  (is_not_cool alpha8)
  (is_not_cool alpha9)
  (is_not_cool alpha10)

  (artifact_at beta1 hall_beta)
  (artifact_at beta2 hall_beta)
  (artifact_at beta3 hall_beta)
  (artifact_at beta4 hall_beta)
  (artifact_at beta5 hall_beta)
  (artifact_at beta6 hall_beta)
  (artifact_at beta7 hall_beta)
  (artifact_at beta8 hall_beta)
  (artifact_at beta9 hall_beta)
  (artifact_at beta10 hall_beta)

  (robot_at light1 entrance)
  (robot_at heavy1 entrance)
  (robot_at drone1 entrance)

  (is_unsealed light1)
  (is_unsealed heavy1)

  (robot_capacity light1 n0)
  (robot_can_carry light1 n0)
  (robot_can_carry light1 n1)
  (robot_can_carry light1 n2)

  (robot_capacity heavy1 n0)
  (robot_can_carry heavy1 n0)
  (robot_can_carry heavy1 n1)
  (robot_can_carry heavy1 n2)
  (robot_can_carry heavy1 n3)
  (robot_can_carry heavy1 n4)
  
  (robot_capacity drone1 n0)
  (robot_can_carry drone1 n0)
  (robot_can_carry drone1 n1)

  (next_capacity n0 n1)
  (next_capacity n1 n2)
  (next_capacity n2 n3)
  (next_capacity n3 n4)
)

(:goal (and
  (artifact_at alpha1 stasis_lab)
  (artifact_at alpha2 stasis_lab)
  (artifact_at alpha3 stasis_lab)
  (artifact_at alpha4 stasis_lab)
  (artifact_at alpha5 stasis_lab)
  (artifact_at alpha6 stasis_lab)
  (artifact_at alpha7 stasis_lab)
  (artifact_at alpha8 stasis_lab)
  (artifact_at alpha9 stasis_lab)
  (artifact_at alpha10 stasis_lab)

  (is_cool alpha1)
  (is_cool alpha2)
  (is_cool alpha3)
  (is_cool alpha4)
  (is_cool alpha5)
  (is_cool alpha6)
  (is_cool alpha7)
  (is_cool alpha8)
  (is_cool alpha9)
  (is_cool alpha10)

  (artifact_at beta1 stasis_lab)
  (artifact_at beta2 stasis_lab)
  (artifact_at beta3 stasis_lab)
  (artifact_at beta4 stasis_lab)
  (artifact_at beta5 stasis_lab)
  (artifact_at beta6 stasis_lab)
  (artifact_at beta7 stasis_lab)
  (artifact_at beta8 stasis_lab)
  (artifact_at beta9 stasis_lab)
  (artifact_at beta10 stasis_lab)

  (is_in_pod beta1)
  (is_in_pod beta2)
  (is_in_pod beta3)
  (is_in_pod beta4)
  (is_in_pod beta5)
  (is_in_pod beta6)
  (is_in_pod beta7)
  (is_in_pod beta8)
  (is_in_pod beta9)
  (is_in_pod beta10)
))
)